{:title "Holy Dev Newsletter April 2022"
 :hide-from-home? true
 :date "2022-04-30"
 :tags ["newsletter"]}

Welcome to the Holy Dev newsletter, which brings you gems I found on the web, updates from my blog, and a few scattered thoughts. You can get the next one into your mailbox if you link:/me/subscribe[subscribe].

== What is happening
I am busy helping folks with their Fulcro projects so I hadn't much time for anything else. I am progressing occasionally with the Fulcro RAD Asami plugin but got delayed by having to work around some limitations of Asami. I am also helping to get the Clojure client for https://www.wolfram.com/language/[Wolfram] to the finish line (we need a new repo, code cleanup, and updated docs).

== Gems from the world wide web
++++
<p><span class="link">👓 <a href="https://azzamsa.com/n/rust-docker/">Tiny and Fast Docker image for Rust Application - AZZAMSA</a> [rust, devops]</span><br /><span style="white-space: pre-line;">Tips: Use a builder image, improve caching and thus compile time with cargo chef, use scratch for the smallest image (here 8MB) or distroless for slightly bigger one (here 30) but with faster recompilation (here 2 vs 9 min). </span></p><p><span class="link">👓 <a href="https://github.com/phronmophobic/viscous">phronmophobic/viscous: pprint that respects your space and time</a> [clojure, library, tool]</span><br /><span style="white-space: pre-line;">An interactive display for your data, similar to the browser' Console - display only a part of the data, page to see more, drill down,.. I haven't tried it but it looks pretty neat. From the site: A visual data inspector/explorer that runs in constant space, time, and screen space.</span></p><p><span class="link">👓 <a href="https://biffweb.com/">Biff</a> [clojure, webdev, library]</span><br /><span style="white-space: pre-line;">An interesting full-stack framework for creating web applications aimed primarily at the lone developer, with the tagline "Launch new projects quickly without getting bogged down in complexity later." There has been a major release now that, among others, significantly simplified the frontend by replacing React and Cljs with <a href="https://htmx.org/">htmx</a>. Htmx is an alternative to SPA, a JS library to easily add interactivity and load and replace parts of the web page from the server via htmx' magical HTML attributes. This is worth exploring as a counterbalance to the SPA craze :). The release also adds support for live dev in prod (transfering and auto-loading changes over rsync). Not for everyone but great for some. (Htmx makes it much easier than JS to add even more interactivity to the pages via its companion lib <a href="https://hyperscript.org/comparison/">Hyperscript - see the comparison</a>.) I guess that if your frontend needs are somewhat limited then HTMX may be a much more productive choice.</span><br /><span style="white-space: pre-line;">More on Biff - <a href="https://xtdb.com/">XTDB</a> for persistent data (e.g. backed by Postgres in prod), Reitit for routing, Malli for enforcing schema, Rum with <a href="https://tailwindcss.com/">Tailwind CSS</a> for server-rendering web pages, Chime for scheduled tasks.</span></p><p><span class="link">👓 <a href="https://cnuernber.github.io/dtype-next/tech.v3.datatype.char-input.html#var-read-json">tech.v3.datatype.char-input documentation</a> [clojure, library]</span><br /><span style="white-space: pre-line;"><strong>dtype-next: lightning fast JSON and CSV parsers</strong><br /></span><br /><span style="white-space: pre-line;">"Lighting fast json parsing without the jackson dependency hairball," included in <a href="https://github.com/cnuernber/dtype-next">dtype-next</a>. It also includes a <a href="https://cnuernber.github.io/dtype-next/tech.v3.datatype.char-input.html#var-read-csv-compat">CSV parser</a> as a faster alternative to clojure.data.csv. Reportedly:</span><br /><span style="white-space: pre-line;"><div class="indented" style="padding-left: 1em">Same speed (or faster with options) as jsonista which by my tests put it about 5-10x faster than clojure.data.json. </div></span><br /><span style="white-space: pre-line;">(In both cases the performance gains stem from not using the pushback reader and writing tight loops in Java. The performance really comes down to how fast you can create maps.)</span><br /><span style="white-space: pre-line;">You can run the JSON parser with :<em>profile :mutable</em> for ± 30% speedup (-> arrays and Java HasMaps).</span></p><p><span class="link">👓 <a href="https://github.com/cnuernber/charred">cnuernber/charred: zero dependency efficient read/write of json and csv data.</a> [clojure, library, data, performance]</span><br /><span style="white-space: pre-line;">Very fast json/ csv encode and decode, a drop-in replacement for clojure.data.csv and clojure.data.json. Same API, much better (5-10x) performance. You can eschew immutable data for additional perfomance boost (possibly 30%).</span><br /><span style="white-space: pre-line;">(Previously reported here in https://holyjak.tumblr.com/post/681241985785430016/techv3datatypechar-input-documentation but not extracted into a standalone library.)</span></p><p><span class="link">👓 <a href="https://github.com/HealthSamurai/matcho">HealthSamurai/matcho: Simpliest pattern matching you've ever seen</a> [clojure, library, testing]</span><br /><span style="white-space: pre-line;">A nice small library for checking that a structure is as expected (you can use simple values, RegExp, spec, predicates), optionally strict. </span></p><p><span class="link">👓 <a href="https://github.com/nytimes/jsonlogic">nytimes/jsonlogic - encode rules in json for sharing, Clj impl</a> [clojure, library, clojurescript, webdev]</span><br /><span style="white-space: pre-line;">Json Logic allows encoding rules in json so they can be shared between frontend and backend. This is a Clojure implementation. As custom operators with multimethods. </span></p><p><span class="link">👓 <a href="https://stackoverflow.blog/2022/04/07/you-should-be-reading-academic-computer-science-papers/">You should be reading academic computer science papers - Stack Overflow Blog</a></span><br /><span style="white-space: pre-line;">Reading papers about programming may help you solve problems better and understand the ways we work more. Papers We Love (and their presentations) might help you with that. </span></p><p><span class="link">👓 <a href="https://medium.com/nightingale/navigating-the-wide-world-of-web-based-data-visualization-libraries-798ea9f536e7">Navigating the Wide World of Data Visualization Libraries</a> [webdev, data visualization, comparison] - <q>Almost everyone has heard of D3, but what about the others?</q></span><br /><span style="white-space: pre-line;">A useful overview (from 2020) of the space of data visualization / charting libraries, categorized by their "level of abstraction" and "API type" (framework specific x JSON x JS ...). Mentions Apache Echarts, Vega, D3, and a number of others.</span></p><p><span class="link">👓 <a href="https://mitpress.mit.edu/books/designed-digital">Designed for Digital | The MIT Press</a> [book, company culture]</span><br /><span style="white-space: pre-line;"><em>Designed for Digita</em>l offers practical advice on digital transformation, with examples that include Amazon, BNY Mellon, DBS Bank, LEGO, Philips, Schneider Electric, USAA, and many other global organizations. Drawing on five years of research and in-depth case studies. Reportedly a great book.</span></p><p><span class="link">👓 <a href="https://www.metosin.fi/blog/packaging-clojure/">Packaging Clojure for Production - Metosin</a> [clojure, learning, devops]</span><br /><span style="white-space: pre-line;">A modern (2022) overview of how to packge Clojure apps for deployment, both frontend and back. Backend: uberjar, Docker, check out the git repo. Frontend: baked into the backend app vs. externally. Mostly general consideration that will help you to pick the options best for you but also concrete examples.</span></p><p><span class="link">👓 <a href="https://dev.to/carlosrafael22/using-refs-in-react-functional-components-part-1-useref-callback-ref-2j5i">Using refs in React functional components (part 1) - useRef + callback ref</a> [webdev, javascript, react]</span><br /><span style="white-space: pre-line;">A great 3-part series introducing using refs in modern react, with the ref prop (with a Ref object or a callback, when to use which), useRef, wrapping a functional component with forwardRef to allow passing in a Ref holder (so that its parent can get hold of a dom ref to its child), useImperativeHandle & more. I knew little about this topic and hooks and this series did a good job of explaining it to me.</span><br /><span style="white-space: pre-line;">Notes:</span><ul><li>useRef creates a generic Ref object that can hold a .current value and can be used for anything, not just dom node refs. useImperativeHandle can then be used to change its value so that you can pass back e.g. a map with multiple dom refs wrapped inside a name -> ref map. (Notice the parent passes in an empty Ref object, we pass back a value containing actual dom ref(s)).</li><li>forwardRef is used because ref is a <a href="https://reactjs.org/warnings/special-props.html">reserved property name used by React and not passed on to the underlying component</a> so you could not pass it from the parent otherwise (but you could pass it instead via a custom property with a different name and not need forwardRef then).</li><li><a href="https://medium.com/trabe/react-useref-hook-b6c9d39e2022">updating a ref is a side effect so it should be done only inside a useEffect (or useLayoutEffect) or inside an event handler</a> (or, of course, useImperativeHandle)</li></ul></p>
++++

+++--+++

Thank you for reading!
