{:title "Holy Dev Newsletter March 2024"
 :hide-from-home? true
 :date "2024-03-21"
 :tags ["newsletter"]
 :asciidoctor {:attributes {#_#_"relfileprefix" "https://blog.jakubholy.net/2024/"}}}

// TODO: 1) Email: send to *self* + subscribers in BCC
// TODO: 2) Email: comment-out the four `//email:` below & fix the MM in the first one & comment-out the subscribe L14, then `bb serve` (not fast! <> utf8), copy & paste into email
// TODO: 3) All **links must be ABSOLUTE** (to work for email)
// TODO: 4) Re-comment the four `//` & publish to blog

Welcome to the Holy Dev newsletter, which brings you gems I found on the web, updates from my blog, and a few scattered thoughts.
//email: (Also https://blog.jakubholy.net/2024/03-newsletter/[available online].)
You can get the next one into your mailbox if you link:/me/subscribe[subscribe].
//email: I am always eager to read your comments and ideas so do not hesitate to press the reply button!

== What is happening

I have spent all my free time with Rama, which resulted in the posts xref:rama-transactions.adoc[Rama: How to achieve a transactional update across partitions] and xref:hands-on-rama-day3.adoc[Hands on Rama, day 3: Foreign keys and data integrity, macros, queries]. Sadly, I did not have much time for Wolframite, but that will need to change, as our Clojurists Together sponsorship quarter is coming up 🙀.

== Gems from the world wide web
++++
<p><span class="link">👓 <a href="https://www.joshwcomeau.com/css/center-a-div/">How To Center a Div</a> [webdev, css]</span><br /><span style="white-space: pre-line;">A very useful overview of different ways to center content with CSS in 2024, and what to use when, including old good margin: auto, flexbox, grid, and more. </span><br /><span style="white-space: pre-line;">Summary: a) If we want to horizontally center a single element without disturbing any of its siblings, we can use the Flow layout auto margin strategy. b) If we have a piece of floating UI, like a modal or a banner, we can center it using Positioned layout and auto margins. c) If we want to center a stack of elements one on top of the other, we can use CSS Grid. d) If we want to center text, we can use text-align. This can be used in conjunction with any of the additional methods. f) Finally, in most other situations, we can use Flexbox.</span></p><p><span class="link">👓 <a href="https://medium.com/@AdityaChatterjee/googles-pregel-graph-processing-system-90341156848a">A quick introduction to Google’s Pregel graph processing system</a> [graph, theory, algorithm] - <q>Pregel was first outlined in a paper published by Google in 2010. It is system for large scale graph processing (think billions of nodes)…</q></span><br /><span style="white-space: pre-line;">A brief, well-written article introducing Google's "Pregel" system for (very) large scale graph processing. Pregel is iterative and runs the same function for each vertex in parallel, allowing it to read messages the vertex got from the previous step or send messages to other vertices (typically along its outgoing edges) for the next step. The article has an example demonstrating this.</span></p><p><span class="link">👓 <a href="https://gist.github.com/ognen/6f445a00b8d6287d9c70f261749ee3c1">Pregel implementation with Rama</a> [rama]</span><br /><span style="white-space: pre-line;">Ognen Ivanovski's implementation of the <a href="https://www.tumblr.com/holyjak/744379180326797312/a-quick-introduction-to-googles-pregel-graph?source=share">Pregel</a> computation system for graphs on top of <a href="https://redplanetlabs.com/learn-rama">Rama</a>, along with connected components and topological sort (for DAGs) as fully distributed algorithms - in < 175 lines. A heavy read without good familiarity with Rama APIs.</span></p><p><span class="link">👓 <a href="https://picocss.com/">Pico CSS • Minimal CSS Framework for semantic HTML</a> [webdev, css, library]</span><br /><span style="white-space: pre-line;">Might be useful. Only CSS, responsive, dark & light modes. Customizable with 130+ CSS variables. Switch between 20 handcrafted color themes and compose with 30+ modular components to tailor the UI to your brand's look and feel.</span></p><p><span class="link">👓 <a href="https://lorenzofox.dev/posts/component-as-infinite-loop/">lorenzofox blog | Coroutines and web components</a> [webdev, javascript, opinion] - <q>Custom elements (web components) modelling with coroutines</q></span><br /><span style="white-space: pre-line;">This was innovative - use JS generators as coroutines (fns that may be paused (i.e. pause themselves via yield) and Sent data on un-pause (since next() can take days that yield will return). Use them to model the life cycle of a component and it's rendering. 🤯</span></p><p><span class="link">👓 <a href="https://dev.to/check/how-moving-from-pandas-to-polars-made-me-write-better-code-without-writing-better-code-52bl">How moving from Pandas to Polars made me write better code without writing better code - DEV Community</a> [data science, performance, experience]</span><br /><span style="white-space: pre-line;">About problems with Pandas, the famous Python dataframe library, and experiences replacing it with Polars, which is built on top of the Arrow memory format and is written in Rust. A great benefit of Polars is it's "lazy api", which postpones execution til the end and injects a query planning and optimization step. </span></p><p><span class="link">👓 <a href="https://www.greptime.com/">Greptime: Cloud-Native TSDB. Anywhere, Any Scale</a> [tool, devops, database, observability]</span><br /><span style="white-space: pre-line;">An interesting project - OSS, cloud-native time-series DB in Rust, at v0.7 with 1.0 expected in August. Can be deployed as a single binary on an IoT device, or a cluster for the metrics and soon logs of your app. Paid by their cloud offering. Highlights: smart indices (created/destroyed on the fly w.r.t usage), efficiency, separate storage and compute (hi, Datomic!), SQL and Prometheus QL (=> can be used as a drop-in replacement for Prometheus in Grafana), distributed and parallel-processing query engine, can be used <a href="https://docs.greptime.com/user-guide/write-data/prometheus">as storage for Prometheus</a>. Write via a gRPC (Go, Java clients), InfluxDB HTTP Line write protocol, OpenTSDB HTTP put, ingest OpenTelemetry metrics via <a href="https://opentelemetry.io/docs/specs/otlp/#otlphttp">OTLP/HTTP</a>, serve as a <a href="https://docs.greptime.com/user-guide/clients/vector">Vector sink</a>,. <a href="https://docs.greptime.com/user-guide/python-scripts/overview">Extend queries with Python</a>. </span></p><p><span class="link">👓 <a href="https://github.com/PEZ/js2clj2js?tab=readme-ov-file">PEZ/js2clj2js: A demo about being cautious with clj->js and js->clj</a> [clojure, performance, clojurescript]</span><br /><span style="white-space: pre-line;">Great article / exploration by Peter Strömberg about various options for working with JSON data in clojure/script. For bigger data, cljs' clj<->js may become too expensive (as demonstrated). A clear winner is to skip JSON.parse and use instead transit/read (at the cost of getting string, not keyword keys) - this can be <a href="https://swannodette.github.io/2014/07/26/transit-clojurescript/">reportedly 20-30x faster</a> than JSON.parse + js->clj. There are also other interesting alternatives, such as cljs-bean that wraps the mutable JS data with Clojure abstractions, so that you can use core fns w/o a conversion (but turning this back to JS is expensive).</span></p>
++++

+++--+++

Thank you for reading!

//email: This newsletter is produced by Jakub Holý, a blogger and programming buddy / mentor for hire.
//email: If you don't want to receive it anymore, simple respond with "unsubscribe" in the subject

