name: Clojure Dependency Checking

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v4

    - name: Check deps
      uses: nnichols/clojure-dependency-update-action@v5
      with:
        github-token: ${{ secrets.github_token }}
